### ISSUE TITLE
Path in example1.py

### ISSUE THREAD

**Issue by lukas-stelzl** [sbottaro/BME#2]
"lustelzl@tbsl025:~/DATA/Projects/BioEn/rna-example/BME/examples$ python example1.py 

Traceback (most recent call last):

File "example1.py", line 6, in <module>
sys.path.append(cwd)

NameError: name 'cwd' is not defined

lustelzl@tbsl025:~/DATA/Projects/BioEn/rna-example/BME/examples$ vim example1.py "

This can be fixed by setting `cwd=sys.path.append(bme_path)`

"lustelzl@tbsl025:~/DATA/Projects/BioEn/rna-example/BME/examples$
python example1.py 
\# Warning: expt average 2-2H5P=0.5000     is smaller than minimum value in simulation 0.9920    

\# exp data: (26, 2)

\# calc data: (20000, 26)

0.982887494545
1.15245524108 0.178512160514
0.96807580576 1.15323415444
lustelzl@tbsl025:~/DATA/Projects/BioEn/rna-example/BME/examples$ "

**Comment by sbottaro** [comment]
Thanks @lukas-stelzl !
